[project]
name = "streamlit-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "html2text>=2025.4.15",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
    "streamlit>=1.44.1",
]
